# Generated by Django 5.2.1 on 2025-05-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_submissaoresumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo_utilizador',
            field=models.CharField(choices=[('Default', 'Default'), ('Avaliador', 'Avaliador'), ('Organizador', 'Organizador')], default='Default', max_length=50),
        ),
    ]
