# Generated by Django 5.2.1 on 2025-06-05 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_inscricaoevento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalidade', models.IntegerField()),
                ('qualidade', models.IntegerField()),
                ('relevancia', models.IntegerField()),
                ('clareza', models.IntegerField()),
                ('comentario', models.TextField()),
                ('decisao', models.CharField(choices=[('aceite', 'Aceite'), ('alteracoes', 'Necessita de alterações'), ('rejeitado', 'Rejeitado')], max_length=20)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.submissaoresumo')),
            ],
            options={
                'unique_together': {('resumo', 'avaliador')},
            },
        ),
    ]
