# Generated by Django 5.2.1 on 2025-06-29 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='core.submissaoresumo')),
            ],
            options={
                'unique_together': {('resumo', 'avaliador')},
            },
        ),
    ]
