# Generated by Django 5.2.1 on 2025-06-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_atribuicao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atribuicao',
            options={'verbose_name': 'Atribuição', 'verbose_name_plural': 'Atribuições'},
        ),
        migrations.AddField(
            model_name='submissaoresumo',
            name='status_final',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aceite', 'Aceite'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20),
        ),
    ]
