# Generated by Django 5.2.1 on 2025-06-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_atribuicao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verificado',
            field=models.BooleanField(default=False),
        ),
    ]
